# Generated by Django 4.2.5 on 2023-09-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='category',
        ),
        migrations.AddField(
            model_name='club',
            name='category',
            field=models.ManyToManyField(to='clubs.category'),
        ),
    ]
