# Generated by Django 4.2.5 on 2023-09-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_product_amount_alter_club_image_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='category',
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='club',
            name='title',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
