# Generated by Django 4.2.5 on 2023-09-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_remove_club_category_alter_club_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
